export const COMMON = {
  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING',
  VAT_VERSION: 'VAT_VERSION',
  TOSTIFY_ALERT_FUNC: 'TOSTIFY_ALERT_FUNC',
  TOSTIFY_ALERT: 'TOSTIFY_ALERT',
  GENERAL_USER_INFO: 'GENERAL_USER_INFO',
  USER_FEEDBACKS:'USER_FEEDBACKS',
  USER_CATEGORY: 'USER_CATEGORY',
  USER_PRODUCTS: 'USER_PRODUCTS',
  SHOP_THEME: 'SHOP_THEME'
}

export const AUTH = {
  SIGNED_IN: 'SIGNED_IN',
  SIGNED_OUT: 'SIGNED_OUT',
  USER_PROFILE: 'USER_PROFILE',
  NOTIFICATION: 'NOTIFICATION',
  MARK_AS_READ: 'MARK_AS_READ',
  USER_SETTINGS: 'USER_SETTINGS'
}


export const ORDER = {
  ALL_ORDERS: 'ALL_ORDERS',
  LIVE_ORDER_DISPLAY: 'LIVE_ORDER_DISPLAY'
}

export const ANALYTICS = {
  ALL_REPORTS: 'ALL_REPORTS',
  NEW_REPORT: 'NEW_REPORT'
}

export const BLACKLIST = {
  BLACKLIST_LIST: 'BLACKLIST'
}

export const WEBHOOK = {
  WEBHOOK_LIST: 'WEBHOOK_LIST',
  WEBHOOK_LOG_LIST: 'WEBHOOK_LOG_LIST'
}

export const QUERIES = {
  QUERIES_LIST: 'QUERIES'
}

export const QUERIE = {
  QUERIE: 'QUERIE'
}

export const PRODUCTS = {
  PRODUCTS: 'PRODUCTS'
}

export const COUPONS = {
  COUPONS: 'COUPONS_FETCH_SUCCESS',
  CURRENT_COUPON: 'CURRENT_COUPON'
}

export const FEEDBACKS = {
  FEEDBACKS: 'FEEDBACKS_FETCH_SUCCESS',
  CURRENT_FEEDBACK: 'CURRENT_FEEDBACK'
}

export const DASHBOARD = {
  BANK_ACCOUNT_TYPE: 'BANK_ACCOUNT_TYPE',
  BANK_ACCOUNT_GRAPH: 'BANK_ACCOUNT_GRAPH',
  CASH_FLOW_GRAPH: 'CASH_FLOW_GRAPH',
  INVOICE_GRAPH: 'INVOICE_GRAPH',
  PROFIT_LOSS: 'PROFIT_LOSS',
  TAXES: 'TAXES',
  EXPENSE_GRAPH: 'EXPENSE_GRAPH',
  REVENUE_GRAPH: 'REVENUE_GRAPH'
}

export const BANK_ACCOUNT = {
  BANK_ACCOUNT_LIST: 'BANK_ACCOUNT_LIST',
  BANK_TRANSACTION_LIST: 'BANK_TRANSACTION_LIST',
  ACCOUNT_TYPE_LIST: 'ACCOUNT_TYPE_LIST',
  CURRENCY_LIST: 'CURRENCY_LIST',
  COUNTRY_LIST: 'COUNTRY_LIST'
}

export const EMPLOYEE = {

}

export const CONTACT = {
  CONTACT_LIST: 'CONTACT_LIST'
}

export const EXPENSE = {
  EXPENSE_LIST: 'EXPENSE_LIST'
}

export const SETTINGS = {

}

export const CUSTOMER_INVOICE = {
  CUSTOMER_INVOICE_LIST: 'CUSTOMER_INVOICE_LIST'
}

export const SUPPLIER_INVOICE = {
  SUPPLIER_INVOICE_LIST: 'SUPPLIER_INVOICE_LIST'
}

export const RECEIPT = {
  RECEIPT_LIST: 'RECEIPT_LIST'
}

export const PRODUCT = {
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  PRODUCT_WHARE_HOUSE: 'PRODUCT_WHARE_HOUSE',
  PRODUCT_VAT_CATEGORY: 'PRODUCT_VAT_CATEGORY',
  PRODUCT_PARENT: 'PRODUCT_PARENT',
  PRODUCT_LIST: 'PRODUCT_LIST'
}


export const PAYMENT = {
  PAYMENT_LIST: 'PAYMENT_LIST'
}

export const USER = {
  USER_LIST: 'USER_LIST'
}

export const VAT = {
  VAT_LIST: 'VAT_LIST',
  VAT_ROW: 'VAT_ROW'
}


export const CATEGORY = {
  ALL_CATEGORY: 'ALL_CATEGORY',
  CURRENT_CATEGORY: 'CURRENT_CATEGORY'
}

